name: engineering-manager-blogs

on:
  schedule:
    - cron: '23 */4 * * *'

jobs:

  build:
  
    runs-on: ubuntu-latest
    environment: new-york-times-rss-top-100  # reuse for AWS creds only 
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Run
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2
        RSSCOMBINE_TITLE: "Engineering Manager Blogs"        
        RSSCOMBINE_DESCRIPTION: "Collection of Engineering Manager Blog RSS Feeds"
        RSSCOMBINE_AUTHOR_EMAIL: "chase.seibert@gmail.com"        
        RSSCOMBINE_AUTHOR_NAME: "Chase Seibert"
        RSSCOMBINE_FEED_LIMIT_PER_FEED: 1
        RSSCOMBINE_FEED_URLS: "https://raw.githubusercontent.com/chase-seibert/engineering-manager-blogs/master/README.md"
        RSSCOMBINE_LINK: "https://github.com/chase-seibert/engineering-manager-blogs"
        RSSCOMBINE_S3_FILENAME: "engineering-manager-blogs.xml"

      run: go run rsscombine.go
